package conceptmaps.model;

// Generated Oct 14, 2014 8:51:13 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "node", catalog = "conceptmapsdb")
public class Node implements java.io.Serializable {

	private String idNode;
	private Concept concept;
	private User user;
	private Integer left;
	private Integer right;
	private Integer width;
	private Integer height;
	private Integer color;

	public Node() {
	}

	public Node(String idNode, Concept concept, User user) {
		this.idNode = idNode;
		this.concept = concept;
		this.user = user;
	}

	public Node(String idNode, Concept concept, User user, Integer left,
			Integer right, Integer width, Integer height, Integer color) {
		this.idNode = idNode;
		this.concept = concept;
		this.user = user;
		this.left = left;
		this.right = right;
		this.width = width;
		this.height = height;
		this.color = color;
	}

	@Id
	@Column(name = "idNode", unique = true, nullable = false, length = 20)
	public String getIdNode() {
		return this.idNode;
	}

	public void setIdNode(String idNode) {
		this.idNode = idNode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idConcept", nullable = false)
	public Concept getConcept() {
		return this.concept;
	}

	public void setConcept(Concept concept) {
		this.concept = concept;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "left")
	public Integer getLeft() {
		return this.left;
	}

	public void setLeft(Integer left) {
		this.left = left;
	}

	@Column(name = "right")
	public Integer getRight() {
		return this.right;
	}

	public void setRight(Integer right) {
		this.right = right;
	}

	@Column(name = "width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "color")
	public Integer getColor() {
		return this.color;
	}

	public void setColor(Integer color) {
		this.color = color;
	}

}
