package conceptmaps.model;

// Generated Oct 14, 2014 9:03:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Relationship generated by hbm2java
 */
@Entity
@Table(name = "relationship", catalog = "conceptmapsdb")
public class Relationship implements java.io.Serializable {

	private String idrelationship;
	private Concept conceptByConcept1;
	private Concept conceptByConcept2;
	private Conceptmaps conceptmaps;
	private MemberAssignment memberAssignment;
	private String name;

	public Relationship() {
	}

	public Relationship(String idrelationship, Concept conceptByConcept1,
			Concept conceptByConcept2) {
		this.idrelationship = idrelationship;
		this.conceptByConcept1 = conceptByConcept1;
		this.conceptByConcept2 = conceptByConcept2;
	}

	public Relationship(String idrelationship, Concept conceptByConcept1,
			Concept conceptByConcept2, Conceptmaps conceptmaps,
			MemberAssignment memberAssignment, String name) {
		this.idrelationship = idrelationship;
		this.conceptByConcept1 = conceptByConcept1;
		this.conceptByConcept2 = conceptByConcept2;
		this.conceptmaps = conceptmaps;
		this.memberAssignment = memberAssignment;
		this.name = name;
	}

	@Id
	@Column(name = "idrelationship", unique = true, nullable = false, length = 20)
	public String getIdrelationship() {
		return this.idrelationship;
	}

	public void setIdrelationship(String idrelationship) {
		this.idrelationship = idrelationship;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concept1", nullable = false)
	public Concept getConceptByConcept1() {
		return this.conceptByConcept1;
	}

	public void setConceptByConcept1(Concept conceptByConcept1) {
		this.conceptByConcept1 = conceptByConcept1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "concept2", nullable = false)
	public Concept getConceptByConcept2() {
		return this.conceptByConcept2;
	}

	public void setConceptByConcept2(Concept conceptByConcept2) {
		this.conceptByConcept2 = conceptByConcept2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idConceptMaps")
	public Conceptmaps getConceptmaps() {
		return this.conceptmaps;
	}

	public void setConceptmaps(Conceptmaps conceptmaps) {
		this.conceptmaps = conceptmaps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMemberAssignment")
	public MemberAssignment getMemberAssignment() {
		return this.memberAssignment;
	}

	public void setMemberAssignment(MemberAssignment memberAssignment) {
		this.memberAssignment = memberAssignment;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
