package conceptmaps.model;

// Generated Nov 9, 2014 4:42:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Concepts generated by hbm2java
 */
@Entity
@Table(name = "concepts", catalog = "conceptmapsdb")
public class Concepts implements java.io.Serializable {

	private Integer id;
	private String name;
	private String class_;
	private String nodeDataArray;
	private String linkDataArray;

	public Concepts() {
	}

	public Concepts(String name) {
		this.name = name;
	}

	public Concepts(String name, String class_, String nodeDataArray,
			String linkDataArray) {
		this.name = name;
		this.class_ = class_;
		this.nodeDataArray = nodeDataArray;
		this.linkDataArray = linkDataArray;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "class")
	public String getClassConcept() {
		return this.class_;
	}

	public void setClassConcept(String class_) {
		this.class_ = class_;
	}

	@Column(name = "nodeDataArray")
	public String getNodeDataArray() {
		return this.nodeDataArray;
	}

	public void setNodeDataArray(String nodeDataArray) {
		this.nodeDataArray = nodeDataArray;
	}

	@Column(name = "linkDataArray")
	public String getLinkDataArray() {
		return this.linkDataArray;
	}

	public void setLinkDataArray(String linkDataArray) {
		this.linkDataArray = linkDataArray;
	}

}
