package conceptmaps.model;

// Generated Nov 10, 2014 10:58:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Concept generated by hbm2java
 */
@Entity
@Table(name = "concept", catalog = "conceptmapsdb")
public class Concept implements java.io.Serializable {

	private String idConcept;
	private String name;
	private String docLink;
	private Set<Node> nodes = new HashSet<Node>(0);
	private Set<Relationship> relationshipsForConceptFrom = new HashSet<Relationship>(
			0);
	private Set<Relationship> relationshipsForConceptTo = new HashSet<Relationship>(
			0);

	public Concept() {
	}

	public Concept(String idConcept, String name, String docLink) {
		this.idConcept = idConcept;
		this.name = name;
		this.docLink = docLink;
	}

	public Concept(String idConcept, String name, String docLink,
			Set<Node> nodes, Set<Relationship> relationshipsForConceptFrom,
			Set<Relationship> relationshipsForConceptTo) {
		this.idConcept = idConcept;
		this.name = name;
		this.docLink = docLink;
		this.nodes = nodes;
		this.relationshipsForConceptFrom = relationshipsForConceptFrom;
		this.relationshipsForConceptTo = relationshipsForConceptTo;
	}

	@Id
	@Column(name = "idConcept", unique = true, nullable = false, length = 35)
	public String getIdConcept() {
		return this.idConcept;
	}

	public void setIdConcept(String idConcept) {
		this.idConcept = idConcept;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "docLink", nullable = false, length = 45)
	public String getDocLink() {
		return this.docLink;
	}

	public void setDocLink(String docLink) {
		this.docLink = docLink;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concept")
	public Set<Node> getNodes() {
		return this.nodes;
	}

	public void setNodes(Set<Node> nodes) {
		this.nodes = nodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conceptByConceptFrom")
	public Set<Relationship> getRelationshipsForConceptFrom() {
		return this.relationshipsForConceptFrom;
	}

	public void setRelationshipsForConceptFrom(
			Set<Relationship> relationshipsForConceptFrom) {
		this.relationshipsForConceptFrom = relationshipsForConceptFrom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conceptByConceptTo")
	public Set<Relationship> getRelationshipsForConceptTo() {
		return this.relationshipsForConceptTo;
	}

	public void setRelationshipsForConceptTo(
			Set<Relationship> relationshipsForConceptTo) {
		this.relationshipsForConceptTo = relationshipsForConceptTo;
	}

}
