package conceptmaps.model;

// Generated Nov 10, 2014 10:58:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name = "link", catalog = "conceptmapsdb")
public class Link implements java.io.Serializable {

	private String idlink;
	private Relationship relationship;
	private String text;
	private String point;
	private int from;
	private int to;

	public Link() {
	}

	public Link(String idlink, Relationship relationship, String point,
			int from, int to) {
		this.idlink = idlink;
		this.relationship = relationship;
		this.point = point;
		this.from = from;
		this.to = to;
	}

	public Link(String idlink, Relationship relationship, String text,
			String point, int from, int to) {
		this.idlink = idlink;
		this.relationship = relationship;
		this.text = text;
		this.point = point;
		this.from = from;
		this.to = to;
	}

	@Id
	@Column(name = "idlink", unique = true, nullable = false, length = 50)
	public String getIdlink() {
		return this.idlink;
	}

	public void setIdlink(String idlink) {
		this.idlink = idlink;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRelationship", nullable = false)
	public Relationship getRelationship() {
		return this.relationship;
	}

	public void setRelationship(Relationship relationship) {
		this.relationship = relationship;
	}

	@Column(name = "text", length = 100)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "point", nullable = false, length = 200)
	public String getPoint() {
		return this.point;
	}

	public void setPoint(String point) {
		this.point = point;
	}

	@Column(name = "from", nullable = false)
	public int getFrom() {
		return this.from;
	}

	public void setFrom(int from) {
		this.from = from;
	}

	@Column(name = "to", nullable = false)
	public int getTo() {
		return this.to;
	}

	public void setTo(int to) {
		this.to = to;
	}

}
