package conceptmaps.model;

// Generated Nov 2, 2014 7:15:49 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkId generated by hbm2java
 */
@Embeddable
public class LinkId implements java.io.Serializable {

	private String idRelationship;
	private String from;
	private String to;

	public LinkId() {
	}

	public LinkId(String idRelationship, String from, String to) {
		this.idRelationship = idRelationship;
		this.from = from;
		this.to = to;
	}

	@Column(name = "idRelationship", nullable = false, length = 20)
	public String getIdRelationship() {
		return this.idRelationship;
	}

	public void setIdRelationship(String idRelationship) {
		this.idRelationship = idRelationship;
	}

	@Column(name = "from", nullable = false, length = 20)
	public String getFrom() {
		return this.from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	@Column(name = "to", nullable = false, length = 20)
	public String getTo() {
		return this.to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinkId))
			return false;
		LinkId castOther = (LinkId) other;

		return ((this.getIdRelationship() == castOther.getIdRelationship()) || (this
				.getIdRelationship() != null
				&& castOther.getIdRelationship() != null && this
				.getIdRelationship().equals(castOther.getIdRelationship())))
				&& ((this.getFrom() == castOther.getFrom()) || (this.getFrom() != null
						&& castOther.getFrom() != null && this.getFrom()
						.equals(castOther.getFrom())))
				&& ((this.getTo() == castOther.getTo()) || (this.getTo() != null
						&& castOther.getTo() != null && this.getTo().equals(
						castOther.getTo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdRelationship() == null ? 0 : this.getIdRelationship()
						.hashCode());
		result = 37 * result
				+ (getFrom() == null ? 0 : this.getFrom().hashCode());
		result = 37 * result + (getTo() == null ? 0 : this.getTo().hashCode());
		return result;
	}

}
