package conceptmaps.model;

// Generated Nov 2, 2014 7:15:49 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name = "link", catalog = "conceptmapsdb")
public class Link implements java.io.Serializable {

	private LinkId id;
	private Node nodeByTo;
	private Node nodeByFrom;
	private Relationship relationship;
	private String point;
	private String text;

	public Link() {
	}

	public Link(LinkId id, Node nodeByTo, Node nodeByFrom,
			Relationship relationship) {
		this.id = id;
		this.nodeByTo = nodeByTo;
		this.nodeByFrom = nodeByFrom;
		this.relationship = relationship;
	}

	public Link(LinkId id, Node nodeByTo, Node nodeByFrom,
			Relationship relationship, String point, String text) {
		this.id = id;
		this.nodeByTo = nodeByTo;
		this.nodeByFrom = nodeByFrom;
		this.relationship = relationship;
		this.point = point;
		this.text = text;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idRelationship", column = @Column(name = "idRelationship", nullable = false, length = 20)),
			@AttributeOverride(name = "from", column = @Column(name = "from", nullable = false, length = 20)),
			@AttributeOverride(name = "to", column = @Column(name = "to", nullable = false, length = 20)) })
	public LinkId getId() {
		return this.id;
	}

	public void setId(LinkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to", nullable = false, insertable = false, updatable = false)
	public Node getNodeByTo() {
		return this.nodeByTo;
	}

	public void setNodeByTo(Node nodeByTo) {
		this.nodeByTo = nodeByTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from", nullable = false, insertable = false, updatable = false)
	public Node getNodeByFrom() {
		return this.nodeByFrom;
	}

	public void setNodeByFrom(Node nodeByFrom) {
		this.nodeByFrom = nodeByFrom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRelationship", nullable = false, insertable = false, updatable = false)
	public Relationship getRelationship() {
		return this.relationship;
	}

	public void setRelationship(Relationship relationship) {
		this.relationship = relationship;
	}

	@Column(name = "point", length = 200)
	public String getPoint() {
		return this.point;
	}

	public void setPoint(String point) {
		this.point = point;
	}

	@Column(name = "text", length = 50)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
