package conceptmaps.model;

// Generated Nov 2, 2014 7:15:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "node", catalog = "conceptmapsdb")
public class Node implements java.io.Serializable {

	private String idNode;
	private Concept concept;
	private User user;
	private String loc;
	private int key;
	private Set<Link> linksForTo = new HashSet<Link>(0);
	private Set<Link> linksForFrom = new HashSet<Link>(0);

	public Node() {
	}

	public Node(String idNode, Concept concept, User user, int key) {
		this.idNode = idNode;
		this.concept = concept;
		this.user = user;
		this.key = key;
	}

	public Node(String idNode, Concept concept, User user, String loc, int key,
			Set<Link> linksForTo, Set<Link> linksForFrom) {
		this.idNode = idNode;
		this.concept = concept;
		this.user = user;
		this.loc = loc;
		this.key = key;
		this.linksForTo = linksForTo;
		this.linksForFrom = linksForFrom;
	}

	@Id
	@Column(name = "idNode", unique = true, nullable = false, length = 20)
	public String getIdNode() {
		return this.idNode;
	}

	public void setIdNode(String idNode) {
		this.idNode = idNode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idConcept", nullable = false)
	public Concept getConcept() {
		return this.concept;
	}

	public void setConcept(Concept concept) {
		this.concept = concept;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "loc", length = 30)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	@Column(name = "key", nullable = false)
	public int getKey() {
		return this.key;
	}

	public void setKey(int key) {
		this.key = key;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeByTo")
	public Set<Link> getLinksForTo() {
		return this.linksForTo;
	}

	public void setLinksForTo(Set<Link> linksForTo) {
		this.linksForTo = linksForTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeByFrom")
	public Set<Link> getLinksForFrom() {
		return this.linksForFrom;
	}

	public void setLinksForFrom(Set<Link> linksForFrom) {
		this.linksForFrom = linksForFrom;
	}

}
