package conceptmaps.model;

// Generated Nov 10, 2014 10:58:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "node", catalog = "conceptmapsdb")
public class Node implements java.io.Serializable {

	private String idNode;
	private Concept concept;
	private User user;
	private String loc;
	private int key;
	private String text;

	public Node() {
	}

	public Node(String idNode, Concept concept, User user, int key) {
		this.idNode = idNode;
		this.concept = concept;
		this.user = user;
		this.key = key;
	}

	public Node(String idNode, Concept concept, User user, String loc, int key,
			String text) {
		this.idNode = idNode;
		this.concept = concept;
		this.user = user;
		this.loc = loc;
		this.key = key;
		this.text = text;
	}

	@Id
	@Column(name = "idNode", unique = true, nullable = false, length = 40)
	public String getIdNode() {
		return this.idNode;
	}

	public void setIdNode(String idNode) {
		this.idNode = idNode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idConcept", nullable = false)
	public Concept getConcept() {
		return this.concept;
	}

	public void setConcept(Concept concept) {
		this.concept = concept;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "loc", length = 30)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	@Column(name = "key", nullable = false)
	public int getKey() {
		return this.key;
	}

	public void setKey(int key) {
		this.key = key;
	}

	@Column(name = "text", length = 45)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
